
import { Product } from '../types';

export const products: Product[] = [
    {
        "Nombre": "Mix Madurados Monticello x 115g",
        "Código": "23658",
        "Cantidad": 1,
        "Marca": "Monticello",
        "Categoría": "Carnes Frías y Pasabocas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$24.000",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Carnes-Fr%C3%ADas-y-Pasabocas/Mix-Madurados-Monticello-x-115g/p/23658_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/23658.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/23658.webp"
    },
    {
        "Nombre": "Salchicha Viena con sabor a limón x 150g c/u",
        "Código": "18834",
        "Cantidad": 1,
        "Marca": "Zenú",
        "Categoría": "Enlatados y Conservas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$12.800",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Enlatados-y-Conservas/Salchicha-Viena-con-sabor-a-lim%C3%B3n-x-150g-c-u/p/18834_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/18834.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/18834.webp"
    },
    {
        "Nombre": "Queso holandés Alpina x 250g",
        "Código": "3637",
        "Cantidad": 1,
        "Marca": "Alpina",
        "Categoría": "Lácteos",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$22.600",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/L%C3%A1cteos/Queso-holand%C3%A9s-Alpina-x-250g/p/3637_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/3637.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/3637.webp"
    },
    {
        "Nombre": "Kit Emergencia Capilar + Cepillo Desenredante",
        "Código": "84542",
        "Cantidad": 1,
        "Marca": "Milagros",
        "Categoría": "- Cuidado Capilar",
        "Tipo_Producto": "PRESTIGIO",
        "Agotado": "No",
        "Precio_Catálogo": "$77.990",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Prestigio/Bienestar/--Cuidado-Capilar/Kit-Emergencia-Capilar-%2B-Cepillo-Desenredante/p/84542_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/84542.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/84542.webp"
    },
    {
        "Nombre": "Salchichas Viena de pollo x 150g c/u",
        "Código": "18835",
        "Cantidad": 1,
        "Marca": "Zenú",
        "Categoría": "Enlatados y Conservas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$12.800",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Enlatados-y-Conservas/Salchichas-Viena-de-pollo-x-150g-c-u/p/18835_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/18835.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/18835.webp"
    },
    {
        "Nombre": "Jet Burbujas Arequipe x 141.6g x 12 unidades x 11.8g c/u ",
        "Código": "46847",
        "Cantidad": 1,
        "Marca": "Jet",
        "Categoría": "Chocolates y Bombones",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$15.000",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Chocolates-y-Bombones/Jet-Burbujas-Arequipe-x-141-6g-x-12-unidades-x-11-8g-c-u-/p/46847_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/46847.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/46847.webp"
    },
    {
        "Nombre": "Natilla Tradicional Maizena x 300g",
        "Código": "21364",
        "Cantidad": 1,
        "Marca": "Maizena",
        "Categoría": "Reposteria",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$10.700",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Reposteria/Natilla-Tradicional-Maizena-x-300g/p/21364_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/21364.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/21364.webp"
    },
    {
        "Nombre": "Natilla Arequipe Maizena x 300g",
        "Código": "6458",
        "Cantidad": 1,
        "Marca": "Maizena",
        "Categoría": "Reposteria",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$10.700",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Reposteria/Natilla-Arequipe-Maizena-x-300g/p/6458_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/6458.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/6458.webp"
    },
    {
        "Nombre": "Jet Leche x12 unds x11gr c/u",
        "Código": "37882",
        "Cantidad": 1,
        "Marca": "Jet",
        "Categoría": "Snacks",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$14.900",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Snacks/Jet-Leche-x12-unds-x11gr-c-u/p/37882_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/37882.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/37882.webp"
    },
    {
        "Nombre": "Salchichas Viena x 150g c/u",
        "Código": "18832",
        "Cantidad": 1,
        "Marca": "Zenú",
        "Categoría": "Enlatados y Conservas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$12.800",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Enlatados-y-Conservas/Salchichas-Viena-x-150g-c-u/p/18832_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/18832.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/18832.webp"
    },
    {
        "Nombre": "La Especial Maní Kraks Bolsa x 140g",
        "Código": "30035",
        "Cantidad": 1,
        "Marca": "La Especial",
        "Categoría": "Snacks",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$5.900",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Snacks/La-Especial-Man%C3%AD-Kraks-Bolsa-x-140g/p/30035_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/30035.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/30035.webp"
    },
    {
        "Nombre": "Salchichas Viena con salsa BBQ sabor a Ron x 160g",
        "Código": "47287",
        "Cantidad": 1,
        "Marca": "Zenú",
        "Categoría": "Enlatados y Conservas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$8.100",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Enlatados-y-Conservas/Salchichas-Viena-con-salsa-BBQ-sabor-a-Ron-x-160g/p/47287_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/47287.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/47287.webp"
    },
    {
        "Nombre": "Kit Biorepolarizador + Ampolleta + Organizador Milagros ",
        "Código": "84460",
        "Cantidad": 1,
        "Marca": "Milagros",
        "Categoría": "- Cuidado Capilar",
        "Tipo_Producto": "PRESTIGIO",
        "Agotado": "No",
        "Precio_Catálogo": "$54.990",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Prestigio/Bienestar/--Cuidado-Capilar/Kit-Biorepolarizador-%2B-Ampolleta-%2B-Organizador-Milagros-/p/84460_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/84460.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/84460.webp"
    },
    {
        "Nombre": "La Especial Minichips x100g",
        "Código": "41665",
        "Cantidad": 1,
        "Marca": "La Especial",
        "Categoría": "Galletas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$7.900",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Galletas/La-Especial-Minichips-x100g/p/41665_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/41665.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/41665.webp"
    },
    {
        "Nombre": "Crema de chocolate Esparcible Jet x 350g",
        "Código": "20502",
        "Cantidad": 1,
        "Marca": "Jet",
        "Categoría": "Esparcibles",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$29.300",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Esparcibles/Crema-de-chocolate-Esparcible-Jet-x-350g/p/20502_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/20502.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/20502.webp"
    },
    {
        "Nombre": "Jamoneta Zenú x 180g c/u",
        "Código": "9041",
        "Cantidad": 1,
        "Marca": "Zenú",
        "Categoría": "Enlatados y Conservas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$22.000",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Enlatados-y-Conservas/Jamoneta-Zen%C3%BA-x-180g-c-u/p/9041_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/9041.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/9041.webp"
    },
    {
        "Nombre": "Infusiones Tosh Surtidas Estuche x 48g x 40unds",
        "Código": "41703",
        "Cantidad": 1,
        "Marca": "Tosh",
        "Categoría": "Bebidas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$22.900",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Bebidas/Infusiones-Tosh-Surtidas-Estuche-x-48g-x-40unds/p/41703_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/41703.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/41703.webp"
    },
    {
        "Nombre": "Chocolatina Jumbo Edición Limitada Big White x 135g",
        "Código": "46599",
        "Cantidad": 1,
        "Marca": "Jumbo",
        "Categoría": "Chocolates y Bombones",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$10.300",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Chocolates-y-Bombones/Chocolatina-Jumbo-Edici%C3%B3n-Limitada-Big-White-x-135g/p/46599_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/46599.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/46599.webp"
    },
    {
        "Nombre": "Chocolatina Jumbo Mix x 12 unds x 60g c/u",
        "Código": "23894",
        "Cantidad": 1,
        "Marca": "Jumbo",
        "Categoría": "Chocolates y Bombones",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$61.500",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Chocolates-y-Bombones/Chocolatina-Jumbo-Mix-x-12-unds-x-60g-c-u/p/23894_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/23894.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/23894.webp"
    },
    {
        "Nombre": "Kit Viajero Anyeluz x 100 ml c/u",
        "Código": "40375",
        "Cantidad": 1,
        "Marca": "Anyeluz",
        "Categoría": "- Cuidado Capilar",
        "Tipo_Producto": "PRESTIGIO",
        "Agotado": "No",
        "Precio_Catálogo": "$53.990",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Prestigio/Bienestar/--Cuidado-Capilar/Kit-Viajero-Anyeluz-x-100-ml-c-u/p/40375_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/40375.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/40375.webp"
    },
    {
        "Nombre": "Chocolatina Jumbo Maní x 12 unds x35gr c/u",
        "Código": "37584",
        "Cantidad": 1,
        "Marca": "Jumbo",
        "Categoría": "Jumbo",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$46.500",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Marcas/Jumbo/Chocolatina-Jumbo-Man%C3%AD-x-12-unds-x35gr-c-u/p/37584_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/37584.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/37584.webp"
    },
    {
        "Nombre": "Chocolatina Montblanc Baileys x 42g",
        "Código": "32693",
        "Cantidad": 1,
        "Marca": "MontBlanc",
        "Categoría": "Chocolates y Bombones",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$42.900",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Chocolates-y-Bombones/Chocolatina-Montblanc-Baileys-x-42g/p/32693_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/32693.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/32693.webp"
    },
    {
        "Nombre": "Chocolatina Montblanc Baileys Nueces Selectas x 60g",
        "Código": "46810",
        "Cantidad": 1,
        "Marca": "MontBlanc",
        "Categoría": "Chocolates y Bombones",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$9.800",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Chocolates-y-Bombones/Chocolatina-Montblanc-Baileys-Nueces-Selectas-x-60g/p/46810_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/46810.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/46810.webp"
    },
    {
        "Nombre": "Wafer Jet Surtida Bandeja x 10unds x 22g c/u",
        "Código": "34517",
        "Cantidad": 1,
        "Marca": "Jet",
        "Categoría": "Chocolates y Bombones",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$20.900",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Chocolates-y-Bombones/Wafer-Jet-Surtida-Bandeja-x-10unds-x-22g-c-u/p/34517_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/34517.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/34517.webp"
    },
    {
        "Nombre": "Bálsamo para labios Nivea Fresa x 4.8g",
        "Código": "38994",
        "Cantidad": 1,
        "Marca": "Nivea",
        "Categoría": "- Cuidado Facial",
        "Tipo_Producto": "PRESTIGIO",
        "Agotado": "No",
        "Precio_Catálogo": "$16.800",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Prestigio/Bienestar/--Cuidado-Facial/B%C3%A1lsamo-para-labios-Nivea-Fresa-x-4-8g/p/38994_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/38994.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/38994.webp"
    },
    {
        "Nombre": "Kit de Mini Perfumes x4 Milagros",
        "Código": "45382",
        "Cantidad": 1,
        "Marca": "Milagros",
        "Categoría": "- Cuidado Capilar",
        "Tipo_Producto": "PRESTIGIO",
        "Agotado": "No",
        "Precio_Catálogo": "$41.990",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Prestigio/Bienestar/--Cuidado-Capilar/Kit-de-Mini-Perfumes-x4-Milagros/p/45382_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/45382.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/45382.webp"
    },
    {
        "Nombre": "Óleo Anti edad Facial y Corporal Anyeluz x 120ml",
        "Código": "45033",
        "Cantidad": 1,
        "Marca": "Anyeluz",
        "Categoría": "- Cuidado Facial",
        "Tipo_Producto": "PRESTIGIO",
        "Agotado": "No",
        "Precio_Catálogo": "$65.990",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Prestigio/Bienestar/--Cuidado-Facial/%C3%93leo-Anti-edad-Facial-y-Corporal-Anyeluz-x-120ml/p/45033_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/45033.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/45033.webp"
    },
    {
        "Nombre": "Kit Glow Box Idunn",
        "Código": "46678",
        "Cantidad": 1,
        "Marca": "Idunn",
        "Categoría": "- Cuidado Facial",
        "Tipo_Producto": "PRESTIGIO",
        "Agotado": "No",
        "Precio_Catálogo": "$97.400",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Prestigio/Bienestar/--Cuidado-Facial/Kit-Glow-Box-Idunn/p/46678_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/46678.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/46678.webp"
    },
    {
        "Nombre": "Bloqueador Facial con Color Milagros x40ml",
        "Código": "40891",
        "Cantidad": 1,
        "Marca": "Milagros",
        "Categoría": "- Cuidado Corporal",
        "Tipo_Producto": "PRESTIGIO",
        "Agotado": "No",
        "Precio_Catálogo": "$53.100",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Prestigio/Bienestar/--Cuidado-Corporal/Bloqueador-Facial-con-Color-Milagros-x40ml/p/40891_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/40891.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/40891.webp"
    },
    {
        "Nombre": "Pack x 4 Capellini Monticello x 454g",
        "Código": "45079",
        "Cantidad": 1,
        "Marca": "Monticello",
        "Categoría": "Pastas y Quinoas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$22.550",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Pastas-y-Quinoas/Pack-x-4-Capellini-Monticello-x-454g/p/45079_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/45079.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/45079.webp"
    },
    {
        "Nombre": "Café Matiz Mujeres Inspiradoras x 240g",
        "Código": "45292",
        "Cantidad": 1,
        "Marca": "Matiz",
        "Categoría": "Bebidas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$28.500",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Bebidas/Caf%C3%A9-Matiz-Mujeres-Inspiradoras-x-240g/p/45292_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/45292.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/45292.webp"
    },
    {
        "Nombre": "Café molido Matiz Baileys x 240g",
        "Código": "36798",
        "Cantidad": 1,
        "Marca": "Matiz",
        "Categoría": "Bebidas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$30.800",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Bebidas/Caf%C3%A9-molido-Matiz-Baileys-x-240g/p/36798_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/36798.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/36798.webp"
    },
    {
        "Nombre": "Pernil de Cerdo Ahumado Zenú x 450g",
        "Código": "98028",
        "Cantidad": 1,
        "Marca": "Zenú",
        "Categoría": "Carnes Frías y Pasabocas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$61.200",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Carnes-Fr%C3%ADas-y-Pasabocas/Pernil-de-Cerdo-Ahumado-Zen%C3%BA-x-450g/p/98028_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/98028.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/98028.webp"
    },
    {
        "Nombre": "Galletas Navidad Noel Cofre x 120g",
        "Código": "46692",
        "Cantidad": 1,
        "Marca": "Noel",
        "Categoría": "Galletas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$19.900",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Galletas/Galletas-Navidad-Noel-Cofre-x-120g/p/46692_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/46692.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/46692.webp"
    },
    {
        "Nombre": "Combo Gourmet® + Maizena",
        "Código": "82071",
        "Cantidad": 1,
        "Marca": "Maizena",
        "Categoría": "Reposteria",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$26.450",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Reposteria/Combo-Gourmet%C2%AE-%2B-Maizena/p/82071_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/82071.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/82071.webp"
    },
    {
        "Nombre": "Kit Milagros x Avemaría",
        "Código": "84748",
        "Cantidad": 1,
        "Marca": "Milagros",
        "Categoría": "- Cuidado Capilar",
        "Tipo_Producto": "PRESTIGIO",
        "Agotado": "No",
        "Precio_Catálogo": "$54.990",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Prestigio/Bienestar/--Cuidado-Capilar/Kit-Milagros-x-Avemar%C3%ADa/p/84748_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/84748.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/84748.webp"
    },
    {
        "Nombre": "Kit Mini Agua de Linos Haka ",
        "Código": "43348",
        "Cantidad": 1,
        "Marca": "Haka",
        "Categoría": "Vive Mejor",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$28.350",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Vive-Mejor/Kit-Mini-Agua-de-Linos-Haka-/p/43348_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/43348.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/43348.webp"
    },
    {
        "Nombre": "Especialidad pernil de cerdo  Zenú x 900g",
        "Código": "19623",
        "Cantidad": 1,
        "Marca": "Zenú",
        "Categoría": "Carnes Frías y Pasabocas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$99.900",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Carnes-Fr%C3%ADas-y-Pasabocas/Especialidad-pernil-de-cerdo-Zen%C3%BA-x-900g/p/19623_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/19623.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/19623.webp"
    },
    {
        "Nombre": "Pavo Casero Zenú x 1.000g",
        "Código": "98003",
        "Cantidad": 1,
        "Marca": "Zenú",
        "Categoría": "Carnes Frías y Pasabocas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$100.500",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Carnes-Fr%C3%ADas-y-Pasabocas/Pavo-Casero-Zen%C3%BA-x-1-000g/p/98003_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/98003.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/98003.webp"
    },
    {
        "Nombre": "Buñuelos Maizena x 300g",
        "Código": "6459",
        "Cantidad": 1,
        "Marca": "Maizena",
        "Categoría": "Reposteria",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$10.700",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Reposteria/Bu%C3%B1uelos-Maizena-x-300g/p/6459_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/6459.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/6459.webp"
    },
    {
        "Nombre": "Natilla Cocada Maizena x 300g",
        "Código": "42039",
        "Cantidad": 1,
        "Marca": "Maizena",
        "Categoría": "Reposteria",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$10.700",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Reposteria/Natilla-Cocada-Maizena-x-300g/p/42039_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/42039.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/42039.webp"
    },
    {
        "Nombre": "Bolsa Navidad Noel 2024 200g",
        "Código": "42118",
        "Cantidad": 1,
        "Marca": "Noel",
        "Categoría": "Galletas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$7.500",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Galletas/Bolsa-Navidad-Noel-2024-200g/p/42118_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/42118.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/42118.webp"
    },
    {
        "Nombre": "Natilla Tres Leches Maizena",
        "Código": "97000",
        "Cantidad": 1,
        "Marca": "Maizena",
        "Categoría": "Reposteria",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$10.700",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Reposteria/Natilla-Tres-Leches-Maizena/p/97000_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/97000.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/97000.webp"
    },
    {
        "Nombre": "Mix Tosh Silvestre X 300G",
        "Código": "6569",
        "Cantidad": 1,
        "Marca": "Tosh",
        "Categoría": "Snacks",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$23.100",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Snacks/Mix-Tosh-Silvestre-X-300G/p/6569_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/6569.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/6569.webp"
    },
    {
        "Nombre": "Ritual gratitud Alpina",
        "Código": "47591",
        "Cantidad": 1,
        "Marca": "Alpina",
        "Categoría": "Esparcibles",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$16.900",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Esparcibles/Ritual-gratitud-Alpina/p/47591_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/47591.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/47591.webp"
    },
    {
        "Nombre": "Arequipe Alpina x 500g",
        "Código": "28354",
        "Cantidad": 1,
        "Marca": "Alpina",
        "Categoría": "Esparcibles",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$14.700",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Esparcibles/Arequipe-Alpina-x-500g/p/28354_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/28354.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/28354.webp"
    },
    {
        "Nombre": "Combo: Yogueta Frutales surtida x24 unds + Toffelo tres leches x 250g x 50 unds",
        "Código": "84513",
        "Cantidad": 1,
        "Marca": "Yogueta",
        "Categoría": "Snacks",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$25.000",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Snacks/Combo%3A-Yogueta-Frutales-surtida-x24-unds-%2B-Toffelo-tres-leches-x-250g-x-50-unds/p/84513_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/84513.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/84513.webp"
    },
    {
        "Nombre": "Combo Panelitas Copelia ",
        "Código": "82127",
        "Cantidad": 1,
        "Marca": "Copelia",
        "Categoría": "Chocolates y Bombones",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$16.600",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Chocolates-y-Bombones/Combo-Panelitas-Copelia-/p/82127_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/82127.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/82127.webp"
    },
    {
        "Nombre": "La Especial Mezcla de Maní con Arándanos x 180g",
        "Código": "4410",
        "Cantidad": 1,
        "Marca": "La Especial",
        "Categoría": "Snacks",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$12.500",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Snacks/La-Especial-Mezcla-de-Man%C3%AD-con-Ar%C3%A1ndanos-x-180g/p/4410_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/4410.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/4410.webp"
    },
    {
        "Nombre": "La Especial Maní Limón Pimienta x 180g",
        "Código": "22479",
        "Cantidad": 1,
        "Marca": "La Especial",
        "Categoría": "Snacks",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$10.700",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Snacks/La-Especial-Man%C3%AD-Lim%C3%B3n-Pimienta-x-180g/p/22479_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/22479.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/22479.webp"
    },
    {
        "Nombre": "Vinagreta Ligera Aderezos x 265g",
        "Código": "47006",
        "Cantidad": 1,
        "Marca": "Aderezos",
        "Categoría": "Salsas Y Aderezos",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$10.900",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Salsas-Y-Aderezos/Vinagreta-Ligera-Aderezos-x-265g/p/47006_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/47006.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/47006.webp"
    },
    {
        "Nombre": "La Especial Maní Kraks Limón x 132g",
        "Código": "32649",
        "Cantidad": 1,
        "Marca": "La Especial",
        "Categoría": "La Especial",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$6.000",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Marcas/La-Especial/La-Especial-Man%C3%AD-Kraks-Lim%C3%B3n-x-132g/p/32649_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/32649.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/32649.webp"
    },
    {
        "Nombre": "Salsa de Tomate Fruco Paga 800g lleva 1.000g",
        "Código": "45459",
        "Cantidad": 1,
        "Marca": "Fruco",
        "Categoría": "Salsas Y Aderezos",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$19.300",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Salsas-Y-Aderezos/Salsa-de-Tomate-Fruco-Paga-800g-lleva-1-000g/p/45459_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/45459.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/45459.webp"
    },
    {
        "Nombre": "Vinagreta Original Aderezos x 1.100g ",
        "Código": "47005",
        "Cantidad": 1,
        "Marca": "Aderezos",
        "Categoría": "Salsas Y Aderezos",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$23.000",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Salsas-Y-Aderezos/Vinagreta-Original-Aderezos-x-1-100g-/p/47005_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/47005.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/47005.webp"
    },
    {
        "Nombre": "Serum corporal milagros x120 ml",
        "Código": "39106",
        "Cantidad": 1,
        "Marca": "Milagros",
        "Categoría": "- Cuidado Capilar",
        "Tipo_Producto": "PRESTIGIO",
        "Agotado": "No",
        "Precio_Catálogo": "$37.800",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Prestigio/Bienestar/--Cuidado-Capilar/Serum-corporal-milagros-x120-ml/p/39106_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/39106.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/39106.webp"
    },
    {
        "Nombre": "Crema de Maní Tosh x 300g",
        "Código": "30032",
        "Cantidad": 1,
        "Marca": "Tosh",
        "Categoría": "Esparcibles",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$16.550",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Esparcibles/Crema-de-Man%C3%AD-Tosh-x-300g/p/30032_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/30032.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/30032.webp"
    },
    {
        "Nombre": "Combo - Paga 2 Lleva 3 - Maizena Colada Arequipe x 180g c/u",
        "Código": "84629",
        "Cantidad": 1,
        "Marca": "Maizena",
        "Categoría": "Reposteria",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$17.600",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Reposteria/Combo---Paga-2-Lleva-3---Maizena-Colada-Arequipe-x-180g-c-u/p/84629_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/84629.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/84629.webp"
    },
    {
        "Nombre": " Combo Sabores Badia",
        "Código": "85245",
        "Cantidad": 1,
        "Marca": "Badia",
        "Categoría": "Salsas Y Aderezos",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$17.600",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Salsas-Y-Aderezos/-Combo-Sabores-Badia/p/85245_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/85245.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/85245.webp"
    },
    {
        "Nombre": "Galletas Noel Cofre Carrusel B x 80g",
        "Código": "46691",
        "Cantidad": 1,
        "Marca": "Noel",
        "Categoría": "Galletas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$15.900",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Galletas/Galletas-Noel-Cofre-Carrusel-B-x-80g/p/46691_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/46691.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/46691.webp"
    },
    {
        "Nombre": "Jumbo Maní 17g x10unds",
        "Código": "46478",
        "Cantidad": 1,
        "Marca": "Jumbo",
        "Categoría": "Chocolates y Bombones",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$15.500",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Chocolates-y-Bombones/Jumbo-Man%C3%AD-17g-x10unds/p/46478_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/46478.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/46478.webp"
    },
    {
        "Nombre": "Mini Pistola Eléctrica De Masaje Portatil ",
        "Código": "42074",
        "Cantidad": 1,
        "Marca": "N/A",
        "Categoría": "- Accesorios de Belleza",
        "Tipo_Producto": "PRESTIGIO",
        "Agotado": "No",
        "Precio_Catálogo": "$31.990",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Prestigio/Accesorios/--Accesorios-de-Belleza/Mini-Pistola-El%C3%A9ctrica-De-Masaje-Portatil-/p/42074_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/42074.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/42074.webp"
    },
    {
        "Nombre": "Vino espumoso Paris De Nuit Brut x 750ml",
        "Código": "47584",
        "Cantidad": 1,
        "Marca": "De Nuit Paris",
        "Categoría": "Bebidas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$63.900",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Bebidas/Vino-espumoso-Paris-De-Nuit-Brut-x-750ml/p/47584_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/47584.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/47584.webp"
    },
    {
        "Nombre": "Aperitivo Aperol Spritz x 750ml",
        "Código": "47582",
        "Cantidad": 1,
        "Marca": "Aperol",
        "Categoría": "Bebidas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$104.500",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Bebidas/Aperitivo-Aperol-Spritz-x-750ml/p/47582_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/47582.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/47582.webp"
    },
    {
        "Nombre": "Arvejas con zanahoria Zenú x 580g",
        "Código": "21303",
        "Cantidad": 1,
        "Marca": "Zenú",
        "Categoría": "Enlatados y Conservas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$9.300",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Enlatados-y-Conservas/Arvejas-con-zanahoria-Zen%C3%BA-x-580g/p/21303_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/21303.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/21303.webp"
    },
    {
        "Nombre": "Chocolisto Cookies & Cream x 160g c/u",
        "Código": "81075",
        "Cantidad": 1,
        "Marca": "Chocolisto",
        "Categoría": "Chocolisto",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$15.300",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Marcas/Chocolisto/Chocolisto-Cookies-%26-Cream-x-160g-c-u/p/81075_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/81075.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/81075.webp"
    },
    {
        "Nombre": "Pollo con antipasto Zenú x 80g c/u",
        "Código": "14038",
        "Cantidad": 1,
        "Marca": "Zenú",
        "Categoría": "Enlatados y Conservas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$17.500",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Enlatados-y-Conservas/Pollo-con-antipasto-Zen%C3%BA-x-80g-c-u/p/14038_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/14038.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/14038.webp"
    },
    {
        "Nombre": "Café Molido Matiz Ron viejo de Caldas x 240g",
        "Código": "46375",
        "Cantidad": 1,
        "Marca": "Matiz",
        "Categoría": "Bebidas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$28.800",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Bebidas/Caf%C3%A9-Molido-Matiz-Ron-viejo-de-Caldas-x-240g/p/46375_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/46375.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/46375.webp"
    },
    {
        "Nombre": "Frijoles con Hogao Zenú x 425g",
        "Código": "46851",
        "Cantidad": 1,
        "Marca": "Zenú",
        "Categoría": "Enlatados y Conservas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$13.200",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Enlatados-y-Conservas/Frijoles-con-Hogao-Zen%C3%BA-x-425g/p/46851_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/46851.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/46851.webp"
    },
    {
        "Nombre": "Whisky King Of Queens x 750ml",
        "Código": "47585",
        "Cantidad": 1,
        "Marca": "De Nuit Paris",
        "Categoría": "Bebidas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$56.600",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Bebidas/Whisky-King-Of-Queens-x-750ml/p/47585_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/47585.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/47585.webp"
    },
    {
        "Nombre": "Café Matiz Escarlata Molido x 340g",
        "Código": "22415",
        "Cantidad": 1,
        "Marca": "Matiz",
        "Categoría": "Bebidas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$34.500",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Bebidas/Caf%C3%A9-Matiz-Escarlata-Molido-x-340g/p/22415_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/22415.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/22415.webp"
    },
    {
        "Nombre": "Estuche x 3 Splash Aromasense x 100 ml",
        "Código": "46729",
        "Cantidad": 1,
        "Marca": "Aromasense",
        "Categoría": "- Fragancias",
        "Tipo_Producto": "PRESTIGIO",
        "Agotado": "No",
        "Precio_Catálogo": "$49.990",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Prestigio/Bienestar/--Fragancias/Estuche-x-3-Splash-Aromasense-x-100-ml/p/46729_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/46729.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/46729.webp"
    },
    {
        "Nombre": "Galletas Noel Cofre Carrusel A x 80g",
        "Código": "46690",
        "Cantidad": 1,
        "Marca": "Noel",
        "Categoría": "Galletas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$15.900",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Galletas/Galletas-Noel-Cofre-Carrusel-A-x-80g/p/46690_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/46690.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/46690.webp"
    },
    {
        "Nombre": "Bálsamo para labios pepti Samy sunset Glam # 01 x 10g",
        "Código": "47389",
        "Cantidad": 1,
        "Marca": "Samy",
        "Categoría": "- Accesorios de Belleza",
        "Tipo_Producto": "PRESTIGIO",
        "Agotado": "No",
        "Precio_Catálogo": "$15.900",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Prestigio/Belleza/--Maquillaje-Labios/B%C3%A1lsamo-para-labios-pepti-Samy-sunset-Glam-%23-01-x-10g/p/47389_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/47389.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/47389.webp"
    },
    {
        "Nombre": "Panetón Feliz Navidad Corona 400g",
        "Código": "46783",
        "Cantidad": 1,
        "Marca": "Corona",
        "Categoría": "Reposteria",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$24.500",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Reposteria/Panet%C3%B3n-Feliz-Navidad-Corona-400g/p/46783_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/46783.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/46783.webp"
    },
    {
        "Nombre": "Bolsa Wafer Jet Cuadritos Cookies & Cream x 140g x10unds",
        "Código": "46598",
        "Cantidad": 1,
        "Marca": "Jet",
        "Categoría": "Chocolates y Bombones",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$12.400",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Chocolates-y-Bombones/Bolsa-Wafer-Jet-Cuadritos-Cookies-%26-Cream-x-140g-x10unds/p/46598_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/46598.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/46598.webp"
    },
    {
        "Nombre": "Spaghetti Doria clásica x 250g c/u",
        "Código": "17237",
        "Cantidad": 1,
        "Marca": "Doria",
        "Categoría": "Pastas y Quinoas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$11.500",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Pastas-y-Quinoas/Spaghetti-Doria-cl%C3%A1sica-x-250g-c-u/p/17237_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/17237.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/17237.webp"
    },
    {
        "Nombre": "Salsa de ciruelas Aderezos x 280g ",
        "Código": "47008",
        "Cantidad": 1,
        "Marca": "Aderezos",
        "Categoría": "Salsas Y Aderezos",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$10.900",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Salsas-Y-Aderezos/Salsa-de-ciruelas-Aderezos-x-280g-/p/47008_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/47008.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/47008.webp"
    },
    {
        "Nombre": "Salsa Mostamiel San Jorge x 200gr",
        "Código": "44365",
        "Cantidad": 1,
        "Marca": "San jorge",
        "Categoría": "Salsas Y Aderezos",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$8.800",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Salsas-Y-Aderezos/Salsa-Mostamiel-San-Jorge-x-200gr/p/44365_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/44365.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/44365.webp"
    },
    {
        "Nombre": "Surtido Doria Clásica",
        "Código": "23563",
        "Cantidad": 1,
        "Marca": "Doria",
        "Categoría": "Pastas y Quinoas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$11.450",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Pastas-y-Quinoas/Surtido-Doria-Cl%C3%A1sica/p/23563_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/23563.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/23563.webp"
    },
    {
        "Nombre": "Aperitivo Aperol + vino Cinzano To Spritz x 1500ml",
        "Código": "47583",
        "Cantidad": 1,
        "Marca": "Aperol",
        "Categoría": "Bebidas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$169.800",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Bebidas/Aperitivo-Aperol-%2B-vino-Cinzano-To-Spritz-x-1500ml/p/47583_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/47583.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/47583.webp"
    },
    {
        "Nombre": "5 Litros Cremhelado Sueño de Navidad",
        "Código": "47275",
        "Cantidad": 1,
        "Marca": "Cremhelado Hogar",
        "Categoría": "Helados Y Postres",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$49.900",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Helados-Y-Postres/5-Litros-Cremhelado-Sue%C3%B1o-de-Navidad/p/47275_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/47275.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/47275.webp"
    },
    {
        "Nombre": "Salsa Bolognese Monticello x 420g",
        "Código": "23663",
        "Cantidad": 1,
        "Marca": "Monticello",
        "Categoría": "Salsas Y Aderezos",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$20.500",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Salsas-Y-Aderezos/Salsa-Bolognese-Monticello-x-420g/p/23663_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/23663.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/23663.webp"
    },
    {
        "Nombre": "Lonchera Surtida Doria x 750g",
        "Código": "23490",
        "Cantidad": 1,
        "Marca": "Doria",
        "Categoría": "Pastas y Quinoas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$19.400",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Pastas-y-Quinoas/Lonchera-Surtida-Doria-x-750g/p/23490_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/23490.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/23490.webp"
    },
    {
        "Nombre": "Pack Surtido Doria x 500g",
        "Código": "45043",
        "Cantidad": 1,
        "Marca": "Doria",
        "Categoría": "Pastas y Quinoas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$15.550",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Pastas-y-Quinoas/Pack-Surtido-Doria-x-500g/p/45043_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/45043.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/45043.webp"
    },
    {
        "Nombre": "La Especial Maní con Sal x 180g",
        "Código": "27292",
        "Cantidad": 1,
        "Marca": "La Especial",
        "Categoría": "La Especial",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$7.100",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Marcas/La-Especial/La-Especial-Man%C3%AD-con-Sal-x-180g/p/27292_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/27292.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/27292.webp"
    },
    {
        "Nombre": "Maíz dulce Zenú x 241g c/u",
        "Código": "16657",
        "Cantidad": 1,
        "Marca": "Zenú",
        "Categoría": "Enlatados y Conservas",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$15.400",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Enlatados-y-Conservas/Ma%C3%ADz-dulce-Zen%C3%BA-x-241g-c-u/p/16657_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/16657.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/16657.webp"
    },
    {
        "Nombre": "Pasabocas Tosh Almendras x 100g",
        "Código": "35508",
        "Cantidad": 1,
        "Marca": "Tosh",
        "Categoría": "Snacks",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$16.300",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Snacks/Pasabocas-Tosh-Almendras-x-100g/p/35508_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/35508.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/35508.webp"
    },
    {
        "Nombre": "Natilla Maracuyá Maizena x 300g",
        "Código": "23446",
        "Cantidad": 1,
        "Marca": "Maizena",
        "Categoría": "Reposteria",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$10.700",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Reposteria/Natilla-Maracuy%C3%A1-Maizena-x-300g/p/23446_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/23446.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/23446.webp"
    },
    {
        "Nombre": "Sal Marina Refisal x 800g",
        "Código": "23899",
        "Cantidad": 1,
        "Marca": "Refisal",
        "Categoría": "Salsas Y Aderezos",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$7.900",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Salsas-Y-Aderezos/Sal-Marina-Refisal-x-800g/p/23899_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/23899.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/23899.webp"
    },
    {
        "Nombre": "Jumbo Maní x90 gr x2 und",
        "Código": "38101",
        "Cantidad": 1,
        "Marca": "Jumbo",
        "Categoría": "Chocolates y Bombones",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$16.900",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Chocolates-y-Bombones/Jumbo-Man%C3%AD-x90-gr-x2-und/p/38101_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/38101.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/38101.webp"
    },
    {
        "Nombre": "Pimienta Negra Molida Badia X 56.7g.",
        "Código": "32616",
        "Cantidad": 1,
        "Marca": "Badia",
        "Categoría": "Salsas Y Aderezos",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$17.500",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Salsas-Y-Aderezos/Pimienta-Negra-Molida-Badia-X-56-7g-/p/32616_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/32616.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/32616.webp"
    },
    {
        "Nombre": "Jet caramel x 18 unds x 6g",
        "Código": "45795",
        "Cantidad": 1,
        "Marca": "Jet",
        "Categoría": "Chocolates y Bombones",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$7.500",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Chocolates-y-Bombones/Jet-caramel-x-18-unds-x-6g/p/45795_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/45795.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/45795.webp"
    },
    {
        "Nombre": "Chocolatina Wafer Jet Mini x 20 unds x 6g",
        "Código": "45760",
        "Cantidad": 1,
        "Marca": "Jet",
        "Categoría": "Chocolates y Bombones",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$10.000",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Chocolates-y-Bombones/Chocolatina-Wafer-Jet-Mini-x-20-unds-x-6g/p/45760_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/45760.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/45760.webp"
    },
    {
        "Nombre": "Chocolatina Jumbo Flow Leche Mini x 10 unds x 18g c/u",
        "Código": "23443",
        "Cantidad": 1,
        "Marca": "Jumbo",
        "Categoría": "Chocolates y Bombones",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$13.050",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Chocolates-y-Bombones/Chocolatina-Jumbo-Flow-Leche-Mini-x-10-unds-x-18g-c-u/p/23443_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/23443.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/23443.webp"
    },
    {
        "Nombre": "Chocolatina Jumbo Maní x 6 unds x 90gr c/u",
        "Código": "37582",
        "Cantidad": 1,
        "Marca": "Jumbo",
        "Categoría": "Chocolates y Bombones",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$50.000",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Chocolates-y-Bombones/Chocolatina-Jumbo-Man%C3%AD-x-6-unds-x-90gr-c-u/p/37582_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/37582.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/37582.webp"
    },
    {
        "Nombre": "Jet Burbujas Cookies & Cream x 115g x 10 unds x 11.5g c/u",
        "Código": "46848",
        "Cantidad": 1,
        "Marca": "Jet",
        "Categoría": "Chocolates y Bombones",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$12.400",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Chocolates-y-Bombones/Jet-Burbujas-Cookies-%26-Cream-x-115g-x-10-unds-x-11-5g-c-u/p/46848_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/46848.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/46848.webp"
    },
    {
        "Nombre": "Chocolatina Montblanc Chocolate blanco almendra x 4 unds x 60g c/u",
        "Código": "24234",
        "Cantidad": 1,
        "Marca": "MontBlanc",
        "Categoría": "Chocolates y Bombones",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$34.900",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Chocolates-y-Bombones/Chocolatina-Montblanc-Chocolate-blanco-almendra-x-4-unds-x-60g-c-u/p/24234_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/24234.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/24234.webp"
    },
    {
        "Nombre": "Jumbo Flow XS Surtida x 14 unds x 9gr c/u",
        "Código": "41443",
        "Cantidad": 1,
        "Marca": "Jumbo",
        "Categoría": "Chocolates y Bombones",
        "Tipo_Producto": "REGULAR",
        "Agotado": "No",
        "Precio_Catálogo": "$7.700",
        "URL_Página": "https://comercio.novaventa.com.co/nautilusb2bstorefront/nautilus/es/COP/Catalogo-Novaventa/Despensa/Chocolates-y-Bombones/Jumbo-Flow-XS-Surtida-x-14-unds-x-9gr-c-u/p/41443_202518",
        "URL_Imagen_Alta_Res": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/1200/41443.webp",
        "URL_Imagen_Carrito": "https://cdn-commerce.novaventa.com.co/commerce/2025/images/c18/96/41443.webp"
    }
]